2018-01-06T06:48:40.608950+00:00 app[api]: Deploy 48fee7ca by user supercoolsmartwhizardofawesome@gmail.com
2018-01-06T06:48:40.966095+00:00 heroku[web.1]: State changed from crashed to starting
2018-01-06T06:48:30.000000+00:00 app[api]: Build succeeded
2018-01-06T06:48:43.226242+00:00 heroku[web.1]: Starting process with command `gunicorn myapp:app --log-file=-`
2018-01-06T06:48:45.019025+00:00 app[web.1]: bash: gunicorn: command not found
2018-01-06T06:48:45.086050+00:00 heroku[web.1]: Process exited with status 127
2018-01-06T06:48:45.101723+00:00 heroku[web.1]: State changed from starting to crashed
2018-01-06T06:48:45.109159+00:00 heroku[web.1]: State changed from crashed to starting
2018-01-06T06:48:49.207500+00:00 heroku[web.1]: Starting process with command `gunicorn myapp:app --log-file=-`
2018-01-06T06:48:53.018011+00:00 app[web.1]: bash: gunicorn: command not found
2018-01-06T06:48:53.253035+00:00 heroku[web.1]: Process exited with status 127
2018-01-06T06:48:53.273923+00:00 heroku[web.1]: State changed from starting to crashed
2018-01-06T06:49:27.929592+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=5572d392-4464-40e6-8d28-44ad0fe8f180 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
2018-01-06T06:49:37.021380+00:00 heroku[web.1]: State changed from crashed to starting
2018-01-06T06:49:38.754033+00:00 heroku[web.1]: Starting process with command `gunicorn myapp:app --log-file=-`
2018-01-06T06:49:40.223321+00:00 app[web.1]: bash: gunicorn: command not found
2018-01-06T06:49:40.281023+00:00 heroku[web.1]: Process exited with status 127
2018-01-06T06:49:40.308875+00:00 heroku[web.1]: State changed from starting to crashed
2018-01-06T06:49:41.070652+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=e5991529-46ec-4a32-ba4e-21e70aa90ef1 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
2018-01-06T06:50:56.000000+00:00 app[api]: Build started by user supercoolsmartwhizardofawesome@gmail.com
2018-01-06T06:50:56.000000+00:00 app[api]: Build failed -- check your build logs
2018-01-06T06:52:44.000000+00:00 app[api]: Build started by user supercoolsmartwhizardofawesome@gmail.com
2018-01-06T06:53:21.377231+00:00 app[api]: Deploy 87d9a857 by user supercoolsmartwhizardofawesome@gmail.com
2018-01-06T06:53:21.377231+00:00 app[api]: Release v10 created by user supercoolsmartwhizardofawesome@gmail.com
2018-01-06T06:52:44.000000+00:00 app[api]: Build succeeded
2018-01-06T06:53:22.797736+00:00 heroku[web.1]: State changed from crashed to starting
2018-01-06T06:53:29.007153+00:00 heroku[web.1]: Starting process with command `gunicorn myapp:app --log-file=-`
2018-01-06T06:53:30.651070+00:00 heroku[web.1]: Restarting
2018-01-06T06:53:30.722146+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [4] [INFO] Starting gunicorn 19.7.1
2018-01-06T06:53:30.722618+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [4] [INFO] Listening at: http://0.0.0.0:32926 (4)
2018-01-06T06:53:30.722723+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [4] [INFO] Using worker: sync
2018-01-06T06:53:30.726122+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [8] [INFO] Booting worker with pid: 8
2018-01-06T06:53:30.732228+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [8] [ERROR] Exception in worker process
2018-01-06T06:53:30.732230+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T06:53:30.732231+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-06T06:53:30.732232+00:00 app[web.1]:     worker.init_process()
2018-01-06T06:53:30.732234+00:00 app[web.1]:     self.load_wsgi()
2018-01-06T06:53:30.732233+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-01-06T06:53:30.732235+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T06:53:30.732236+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T06:53:30.732238+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T06:53:30.732239+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T06:53:30.732240+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T06:53:30.732241+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T06:53:30.732242+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T06:53:30.732243+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T06:53:30.732244+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T06:53:30.732246+00:00 app[web.1]:     __import__(module)
2018-01-06T06:53:30.732247+00:00 app[web.1]: ModuleNotFoundError: No module named 'myapp'
2018-01-06T06:53:30.732426+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-01-06T06:53:30.749815+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [9] [INFO] Booting worker with pid: 9
2018-01-06T06:53:30.754277+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [9] [ERROR] Exception in worker process
2018-01-06T06:53:30.754280+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T06:53:30.754282+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-06T06:53:30.754283+00:00 app[web.1]:     worker.init_process()
2018-01-06T06:53:30.754284+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-01-06T06:53:30.754285+00:00 app[web.1]:     self.load_wsgi()
2018-01-06T06:53:30.754287+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T06:53:30.754287+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T06:53:30.754289+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T06:53:30.754290+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T06:53:30.754291+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T06:53:30.754297+00:00 app[web.1]: ModuleNotFoundError: No module named 'myapp'
2018-01-06T06:53:30.754403+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [9] [INFO] Worker exiting (pid: 9)
2018-01-06T06:53:30.870773+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-01-06T06:53:30.754292+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T06:53:30.754293+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T06:53:30.754294+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T06:53:30.754295+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T06:53:30.870688+00:00 app[web.1]: [2018-01-06 06:53:30 +0000] [4] [INFO] Shutting down: Master
2018-01-06T06:53:30.754296+00:00 app[web.1]:     __import__(module)
2018-01-06T06:53:30.951862+00:00 heroku[web.1]: Process exited with status 3
2018-01-06T06:53:34.362136+00:00 heroku[web.1]: Starting process with command `gunicorn myapp:app --log-file=-`
2018-01-06T06:53:36.393288+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [4] [INFO] Starting gunicorn 19.7.1
2018-01-06T06:53:36.394132+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [4] [INFO] Listening at: http://0.0.0.0:38131 (4)
2018-01-06T06:53:36.394326+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [4] [INFO] Using worker: sync
2018-01-06T06:53:36.398061+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [8] [INFO] Booting worker with pid: 8
2018-01-06T06:53:36.402409+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [8] [ERROR] Exception in worker process
2018-01-06T06:53:36.402413+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-06T06:53:36.402412+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T06:53:36.402415+00:00 app[web.1]:     worker.init_process()
2018-01-06T06:53:36.402416+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-01-06T06:53:36.402417+00:00 app[web.1]:     self.load_wsgi()
2018-01-06T06:53:36.402418+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T06:53:36.402421+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T06:53:36.402422+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T06:53:36.402423+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T06:53:36.402424+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T06:53:36.402425+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T06:53:36.402426+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T06:53:36.402427+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T06:53:36.402428+00:00 app[web.1]:     __import__(module)
2018-01-06T06:53:36.402433+00:00 app[web.1]: ModuleNotFoundError: No module named 'myapp'
2018-01-06T06:53:36.402563+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-01-06T06:53:36.431938+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [4] [INFO] Shutting down: Master
2018-01-06T06:53:36.432099+00:00 app[web.1]: [2018-01-06 06:53:36 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-01-06T06:53:36.402419+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T06:53:36.551799+00:00 heroku[web.1]: State changed from starting to crashed
2018-01-06T06:53:36.524442+00:00 heroku[web.1]: Process exited with status 3
2018-01-06T06:53:41.058305+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=7e2c52a8-7763-41f9-bfd7-a6bda572c13f fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
2018-01-06T06:53:48.449303+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=53524121-dcd7-4dad-9247-cf3fe5935414 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
