2018-01-06T08:36:19.974999+00:00 heroku[web.1]: Starting process with command `gunicorn Permute:app`
2018-01-06T08:36:23.087574+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [4] [INFO] Starting gunicorn 19.7.1
2018-01-06T08:36:23.088420+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [4] [INFO] Listening at: http://0.0.0.0:12779 (4)
2018-01-06T08:36:23.088595+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [4] [INFO] Using worker: sync
2018-01-06T08:36:23.094037+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [8] [INFO] Booting worker with pid: 8
2018-01-06T08:36:23.107182+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [8] [ERROR] invalid syntax (Permute.py, line 87)
2018-01-06T08:36:23.107185+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.107187+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T08:36:23.107188+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T08:36:23.107190+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T08:36:23.107191+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T08:36:23.107192+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T08:36:23.107193+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T08:36:23.107194+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T08:36:23.107195+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T08:36:23.107196+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T08:36:23.107197+00:00 app[web.1]:     __import__(module)
2018-01-06T08:36:23.107198+00:00 app[web.1]:   File "/app/Permute.py", line 87
2018-01-06T08:36:23.107200+00:00 app[web.1]:     with open ('filelanding.csv', 'r', newline='') as f_in, with open('fileoutput.csv', 'w') as f_out, with open('announcer.csv', 'r') as ref:
2018-01-06T08:36:23.107201+00:00 app[web.1]:                                                                ^
2018-01-06T08:36:23.107254+00:00 app[web.1]: SyntaxError: invalid syntax
2018-01-06T08:36:23.108358+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [8] [ERROR] Exception in worker process
2018-01-06T08:36:23.108360+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.108362+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T08:36:23.108363+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T08:36:23.108364+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T08:36:23.108365+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T08:36:23.108367+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T08:36:23.108368+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T08:36:23.108369+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T08:36:23.108370+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T08:36:23.108371+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T08:36:23.108372+00:00 app[web.1]:     __import__(module)
2018-01-06T08:36:23.108373+00:00 app[web.1]:   File "/app/Permute.py", line 87
2018-01-06T08:36:23.108376+00:00 app[web.1]:                                                                ^
2018-01-06T08:36:23.108374+00:00 app[web.1]:     with open ('filelanding.csv', 'r', newline='') as f_in, with open('fileoutput.csv', 'w') as f_out, with open('announcer.csv', 'r') as ref:
2018-01-06T08:36:23.108404+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-01-06T08:36:23.108402+00:00 app[web.1]: 
2018-01-06T08:36:23.108377+00:00 app[web.1]: SyntaxError: invalid syntax
2018-01-06T08:36:23.108405+00:00 app[web.1]: 
2018-01-06T08:36:23.108406+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.108407+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-06T08:36:23.108408+00:00 app[web.1]:     worker.init_process()
2018-01-06T08:36:23.108409+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-01-06T08:36:23.108410+00:00 app[web.1]:     self.load_wsgi()
2018-01-06T08:36:23.108411+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 148, in load_wsgi
2018-01-06T08:36:23.108413+00:00 app[web.1]:     self.reloader.add_extra_file(exc_val.filename)
2018-01-06T08:36:23.108414+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'add_extra_file'
2018-01-06T08:36:23.108570+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [8] [INFO] Worker exiting (pid: 8)
2018-01-06T08:36:23.136103+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [9] [INFO] Booting worker with pid: 9
2018-01-06T08:36:23.152396+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [9] [ERROR] invalid syntax (Permute.py, line 87)
2018-01-06T08:36:23.152399+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.152401+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T08:36:23.152402+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T08:36:23.152404+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T08:36:23.152406+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T08:36:23.152405+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T08:36:23.152407+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T08:36:23.152408+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T08:36:23.152409+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T08:36:23.152410+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T08:36:23.152411+00:00 app[web.1]:     __import__(module)
2018-01-06T08:36:23.152412+00:00 app[web.1]:   File "/app/Permute.py", line 87
2018-01-06T08:36:23.152414+00:00 app[web.1]:     with open ('filelanding.csv', 'r', newline='') as f_in, with open('fileoutput.csv', 'w') as f_out, with open('announcer.csv', 'r') as ref:
2018-01-06T08:36:23.152415+00:00 app[web.1]:                                                                ^
2018-01-06T08:36:23.157627+00:00 app[web.1]: SyntaxError: invalid syntax
2018-01-06T08:36:23.158740+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [9] [ERROR] Exception in worker process
2018-01-06T08:36:23.158743+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.158744+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 135, in load_wsgi
2018-01-06T08:36:23.158746+00:00 app[web.1]:     self.wsgi = self.app.wsgi()
2018-01-06T08:36:23.158750+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 65, in load
2018-01-06T08:36:23.158748+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/base.py", line 67, in wsgi
2018-01-06T08:36:23.158749+00:00 app[web.1]:     self.callable = self.load()
2018-01-06T08:36:23.158751+00:00 app[web.1]:     return self.load_wsgiapp()
2018-01-06T08:36:23.158752+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/app/wsgiapp.py", line 52, in load_wsgiapp
2018-01-06T08:36:23.158753+00:00 app[web.1]:     return util.import_app(self.app_uri)
2018-01-06T08:36:23.158754+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/util.py", line 352, in import_app
2018-01-06T08:36:23.158755+00:00 app[web.1]:     __import__(module)
2018-01-06T08:36:23.158756+00:00 app[web.1]:   File "/app/Permute.py", line 87
2018-01-06T08:36:23.158758+00:00 app[web.1]:     with open ('filelanding.csv', 'r', newline='') as f_in, with open('fileoutput.csv', 'w') as f_out, with open('announcer.csv', 'r') as ref:
2018-01-06T08:36:23.158759+00:00 app[web.1]:                                                                ^
2018-01-06T08:36:23.158760+00:00 app[web.1]: SyntaxError: invalid syntax
2018-01-06T08:36:23.158761+00:00 app[web.1]: 
2018-01-06T08:36:23.158763+00:00 app[web.1]: During handling of the above exception, another exception occurred:
2018-01-06T08:36:23.158764+00:00 app[web.1]: 
2018-01-06T08:36:23.158765+00:00 app[web.1]: Traceback (most recent call last):
2018-01-06T08:36:23.158766+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/arbiter.py", line 578, in spawn_worker
2018-01-06T08:36:23.158773+00:00 app[web.1]:     worker.init_process()
2018-01-06T08:36:23.158775+00:00 app[web.1]:     self.load_wsgi()
2018-01-06T08:36:23.158774+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 126, in init_process
2018-01-06T08:36:23.158776+00:00 app[web.1]:   File "/app/.heroku/python/lib/python3.6/site-packages/gunicorn/workers/base.py", line 148, in load_wsgi
2018-01-06T08:36:23.158778+00:00 app[web.1]:     self.reloader.add_extra_file(exc_val.filename)
2018-01-06T08:36:23.158817+00:00 app[web.1]: AttributeError: 'NoneType' object has no attribute 'add_extra_file'
2018-01-06T08:36:23.159034+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [9] [INFO] Worker exiting (pid: 9)
2018-01-06T08:36:23.275993+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [4] [INFO] Shutting down: Master
2018-01-06T08:36:23.276958+00:00 app[web.1]: [2018-01-06 08:36:23 +0000] [4] [INFO] Reason: Worker failed to boot.
2018-01-06T08:36:23.450889+00:00 heroku[web.1]: Process exited with status 3
2018-01-06T08:36:23.486941+00:00 heroku[web.1]: State changed from starting to crashed
2018-01-06T08:36:35.369057+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=5778ee57-1325-455e-8f02-66c3b0a47349 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
2018-01-06T08:38:02.817409+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=a030b399-c0bd-4c95-9ee5-56cca09e23c4 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
2018-01-06T08:38:04.015428+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=arenarolodex.herokuapp.com request_id=825dbb0c-451a-44ab-8001-a004fac88a99 fwd="198.27.173.78" dyno= connect= service= status=503 bytes= protocol=https
